### ISSUE TITLE
codeviz fails to run on specific machines/repos?

### ISSUE THREAD

**Issue by simzer** [vizzuhq/codeviz#3]
Webwiew console:
```
Uncaught (in promise) Error: error: invalid config parameter: data
    at vizzu.min.js:1:32094
    at vizzu.min.js:1:33791
    at Vizzu.setValue (vizzu.min.js:1:32573)
    at vizzu.min.js:1:32274
    at Array.forEach (<anonymous>)
    at Vizzu.iterateObject (vizzu.min.js:1:32161)
    at Vizzu.setConfig (vizzu.min.js:1:33729)
    at Vizzu.animStep (vizzu.min.js:1:34715)
    at vizzu.min.js:1:34346
(anonymous) @ vizzu.min.js:1
(anonymous) @ vizzu.min.js:1
setValue @ vizzu.min.js:1
(anonymous) @ vizzu.min.js:1
iterateObject @ vizzu.min.js:1
setConfig @ vizzu.min.js:1
animStep @ vizzu.min.js:1
(anonymous) @ vizzu.min.js:1
postMessage (async)
(anonymous) @ main.js:122
channel.port1.onmessage @ main.js:121
```

**Comment by schaumb** [comment]
Cannot reproduce
